name: Test pymaic Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install pixi
      run: |
        curl -fsSL https://pixi.sh/install.sh | bash
    - name: Add pixi to PATH
      run: echo "$HOME/.pixi/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pixi install
    - name: Run pymaic function
      run: |
        maic -f tests/test_input.txt -o output -v
    - name: Verify output
      run: |
        if [ ! -d "output" ]; then
          echo "Output directory not found!"
          exit 1
        fi
    - name: Clean up output directory
      run: |
        rm -rf output
