name: Pymaic Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-pymaic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.4.1

    - name: Install dependencies
      run: pixi install

    - name: Activate Pixi environment and run maic command
      run: |
        eval "$(pixi shell --print-activation)"
        which maic
        maic -f tests/test_input.txt -o output

    - name: Check output
      run: |
        if [ -d output ] && [ "$(ls -A output)" ]; then
          echo "maic command ran successfully"
          ls -R output
        else
          echo "maic command failed to produce output"
          exit 1
        fi

    - name: Clean up
      run: rm -rf output
